// Generated by CoffeeScript 1.3.1

(function($) {
  return $.ender({
    ajaj: function(options) {
      options.method || (options.method = 'GET');
      options.type = 'json';
      options.headers || (options.headers = {});
      if (options.data && typeof options.data !== 'string') {
        options.headers['Content-Type'] = 'application/json';
        options.data = JSON.stringify(options.data);
      }
      return $.ajax(options);
    }
  });
})(ender);
